name: SpigotTesting
version: ${project.version}
authors: [Agentred100, jugglingman456, SimonOrJ]
description: Arcane Testing Plugin with Spigot
main: com.arcaneminecraft.testing.SpigotTesting
website: https://arcaneminecraft.com/

commands:
  f:
    description: Fireworks (Arcane's first anniversity command)
  doge:
    description: Doge command

permissions:
  arcane.f:
    description: fireworks
    default: op
