name: SpigotTesting
version: ${project.version}
authors: [SimonOrJ]
description: Arcane Testing Plugin with Spigot
main: com.arcaneminecraft.testing.SpigotTesting
website: https://arcaneminecraft.com/

commands:
  christmas:
    aliases: [present]
    description: Merry Christmas! A free shulker box with an elytra in it!
  nbt:
    description: test command to check nbt data.

permissions:
  arcane.christmas:
    description: The christmas event!
    default: false
